const path = require("path");
const merge = require("webpack-merge");

const SRC_DIR = path.resolve(__dirname, "../../src");
const DIST_DIR = path.resolve(__dirname, "../../dist");
const CLIENT_SRC_DIR = path.join(SRC_DIR, "./client");
const SERVER_SRC_DIR = path.join(SRC_DIR, "./server");
const CLIENT_BUILD_DIR = path.join(DIST_DIR, "./assets");
const SERVER_BUILD_DIR = path.join(DIST_DIR, "./server");

// cf. https://webpack.js.org/ for webpack documentation:
const base = {
	module: {
		rules: [
			{
				test: /\.js[x]?$/,
				include: SRC_DIR,
				use: ["babel-loader"]
			},
			{
				test: /\.(jp[e]?g|png|gif|svg|html|ico|eot|ttf|woff|woff2|otf)$/i,
				use: {
					loader: "file-loader",
					options: {
						name: "assets/[name].[hash].[ext]"
					}
				}
			}
		]
	},
	resolve: {
		alias: {
			public: path.resolve(__dirname, "../../public")
		},
		modules: [SRC_DIR, path.join(SRC_DIR, "./shared"), "node_modules"],
		extensions: [".js", ".jsx"]
	}
};

const cssLoaders = [
	{
		loader: "css-loader",
		options: {
			modules: true,
			minimize: true,
			importLoaders: 1,
			localIdentName: "[name]__[local]___[hash:base64:5]"
		}
	},
	{
		loader: "postcss-loader",
		options: {
			plugins: [
				// postcss-cssnext already includes postcss-nested:
				// same for autoprefixer
				// see. http://cssnext.io/features/
				require("postcss-cssnext")({
					// autoprefixer browsers env:
					browsers: ["> 1%", "last 2 versions"]
				})
			]
		}
	}
];

const baseClient = merge(
	{
		name: "client",
		target: "web",
		entry: {
			// The key is the chunk name. The value can be a string or an array.
			// But for merging purpose, I used to give an array as value to allow webpack-merge
			// to easily merge value into the array (for hmr entries for example).
			app: [CLIENT_SRC_DIR]
		},
		output: {
			path: CLIENT_BUILD_DIR,
			publicPath: "/"
		}
	},
	base
);

const baseServer = merge(
	{
		name: "server",
		target: "node",
		node: {
			// cf. https://webpack.js.org/configuration/node/#node-__dirname
			// __dirname: false; allows to overwrite default behavior of __dirname
			// constants when __dirname is called inside a bundle generated by webpack
			// By default, it takes the "mock" value which corresponds to "/". By setting it to
			// true, __dirname is relative to the file which calls __dirname :)
			__dirname: true
		},
		externals: [
			/^[a-z\-0-9]+$/,
			{
				"react-dom/server": true // TODO check with react 16
			}
		],
		entry: {
			app: [SERVER_SRC_DIR]
		},
		output: {
			filename: "[name].js",
			path: SERVER_BUILD_DIR,
			libraryTarget: "commonjs2",
			publicPath: CLIENT_BUILD_DIR
		}
	},
	base
);

module.exports = {
	baseClient,
	baseServer,
	cssLoaders
};
